jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker build -t pwabuilderDocsApi . 
    displayName: Build docker image
  - script: docker tag pwabuilderDocsApi $(dockerId).azurecr.io/pwabuilderDocsApi:$(Build.SourceVersion)
    displayName: Re-tag docker image
  - script: docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    displayName: Authenticate ACR
  - script: docker push $(dockerId).azurecr.io/pwabuilderDocsApi:$(Build.SourceVersion)
    displayName: Push docker image 