jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: docker build --target $(targetName) -t manifoldapi . 
    displayName: Build docker image
  - bash: docker tag manifoldapi $(dockerId).azurecr.io/manifoldapi:$(Build.SourceVersion)
    displayName: Re-tag docker image
  - bash: docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    displayName: Authenticate ACR
  - bash: docker push $(dockerId).azurecr.io/manifoldapi:$(Build.SourceVersion)
    displayName: Push docker image 